module Cake
  APPLICATION_FEE = 0.050
  STRIPE_FEE = 0.029

  DISQUS_SHORTNAME = ENV["DISQUS_SHORTNAME"] || 'bismarktest'
  DISQUS_CAMPAIGNS_CATEGORY_ID = ENV["DISQUS_CAMPAIGNS_CATEGORY_ID"] || '3415482'
  DISQUS_PLEDGES_CATEGORY_ID = ENV["DISQUS_PLEDGES_CATEGORY_ID"] || '3415483'
end