module Cake
  APPLICATION_FEE = 0.050
  STRIPE_FEE = 0.029

  DISQUS_SHORTNAME = ENV["DISQUS_SHORTNAME"]
  DISQUS_CAMPAIGNS_CATEGORY_ID = ENV["DISQUS_CAMPAIGNS_CATEGORY_ID"]
  DISQUS_PLEDGES_CATEGORY_ID = ENV["DISQUS_PLEDGES_CATEGORY_ID"]
  IFRAME_HOST = ENV['CAKE_IFRAME_HOST']
end