campaign_end:
  # every:
  #   - "1m"
  cron: "* * * * * America/New_York"
  class: "ResqueSchedule::CampaignEnd"
  queue: high
  description: "Triggers the @campaign.end method on campaigns that have reach their end_date"

campaign_missed_launch:
  # every:
  #   - "1d"
  cron: "0 0 * * * America/New_York"
  class: "ResqueSchedule::CampaignMissedLaunch"
  queue: low
  description: "Triggers the @campaign.missed_launch_date method on campaigns that have missed their launch_date"

campaigns_incomplete:
  # at: 4:30
  cron: "30 4 * * * America/New_York"
  class: "ResqueSchedule::CampaignsUncompleted"
  queue: high
  description: "Deletes all incomplete campaigns."

pledges_incomplete:
  # at: 4:30
  cron: "30 4 * * * America/New_York"
  class: "ResqueSchedule::PledgesUncompleted"
  queue: high
  description: "Deletes all incomplete pledges."

notify_pledges_fully_subscribed:
  # every:
  #   - "30m"
  cron: "30 * * * * America/New_York"
  class: "ResqueSchedule::PledgeFullySubscribed"
  queue: medium
  description: "Notifies the SPs when their pledges have been fully subscribed"

transfer_payments:
  # every:
  #   - "1d"
  cron: "0 0 * * * America/New_York"
  class: "ResqueSchedule::TranferPayments"
  queue: high
  description: "Transfers funds to fundraisers's Stripe accounts"


