require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CakestersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cakester. As you add validations to Cakester, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CakestersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cakesters as @cakesters" do
      cakester = Cakester.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cakesters)).to eq([cakester])
    end
  end

  describe "GET show" do
    it "assigns the requested cakester as @cakester" do
      cakester = Cakester.create! valid_attributes
      get :show, {:id => cakester.to_param}, valid_session
      expect(assigns(:cakester)).to eq(cakester)
    end
  end

  describe "GET new" do
    it "assigns a new cakester as @cakester" do
      get :new, {}, valid_session
      expect(assigns(:cakester)).to be_a_new(Cakester)
    end
  end

  describe "GET edit" do
    it "assigns the requested cakester as @cakester" do
      cakester = Cakester.create! valid_attributes
      get :edit, {:id => cakester.to_param}, valid_session
      expect(assigns(:cakester)).to eq(cakester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cakester" do
        expect {
          post :create, {:cakester => valid_attributes}, valid_session
        }.to change(Cakester, :count).by(1)
      end

      it "assigns a newly created cakester as @cakester" do
        post :create, {:cakester => valid_attributes}, valid_session
        expect(assigns(:cakester)).to be_a(Cakester)
        expect(assigns(:cakester)).to be_persisted
      end

      it "redirects to the created cakester" do
        post :create, {:cakester => valid_attributes}, valid_session
        expect(response).to redirect_to(Cakester.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cakester as @cakester" do
        post :create, {:cakester => invalid_attributes}, valid_session
        expect(assigns(:cakester)).to be_a_new(Cakester)
      end

      it "re-renders the 'new' template" do
        post :create, {:cakester => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cakester" do
        cakester = Cakester.create! valid_attributes
        put :update, {:id => cakester.to_param, :cakester => new_attributes}, valid_session
        cakester.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cakester as @cakester" do
        cakester = Cakester.create! valid_attributes
        put :update, {:id => cakester.to_param, :cakester => valid_attributes}, valid_session
        expect(assigns(:cakester)).to eq(cakester)
      end

      it "redirects to the cakester" do
        cakester = Cakester.create! valid_attributes
        put :update, {:id => cakester.to_param, :cakester => valid_attributes}, valid_session
        expect(response).to redirect_to(cakester)
      end
    end

    describe "with invalid params" do
      it "assigns the cakester as @cakester" do
        cakester = Cakester.create! valid_attributes
        put :update, {:id => cakester.to_param, :cakester => invalid_attributes}, valid_session
        expect(assigns(:cakester)).to eq(cakester)
      end

      it "re-renders the 'edit' template" do
        cakester = Cakester.create! valid_attributes
        put :update, {:id => cakester.to_param, :cakester => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cakester" do
      cakester = Cakester.create! valid_attributes
      expect {
        delete :destroy, {:id => cakester.to_param}, valid_session
      }.to change(Cakester, :count).by(-1)
    end

    it "redirects to the cakesters list" do
      cakester = Cakester.create! valid_attributes
      delete :destroy, {:id => cakester.to_param}, valid_session
      expect(response).to redirect_to(cakesters_url)
    end
  end

end
