require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FrSponsorsController do

  # This should return the minimal set of attributes required to create a valid
  # FrSponsor. As you add validations to FrSponsor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FrSponsorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fr_sponsors as @fr_sponsors" do
      fr_sponsor = FrSponsor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fr_sponsors).should eq([fr_sponsor])
    end
  end

  describe "GET show" do
    it "assigns the requested fr_sponsor as @fr_sponsor" do
      fr_sponsor = FrSponsor.create! valid_attributes
      get :show, {:id => fr_sponsor.to_param}, valid_session
      assigns(:fr_sponsor).should eq(fr_sponsor)
    end
  end

  describe "GET new" do
    it "assigns a new fr_sponsor as @fr_sponsor" do
      get :new, {}, valid_session
      assigns(:fr_sponsor).should be_a_new(FrSponsor)
    end
  end

  describe "GET edit" do
    it "assigns the requested fr_sponsor as @fr_sponsor" do
      fr_sponsor = FrSponsor.create! valid_attributes
      get :edit, {:id => fr_sponsor.to_param}, valid_session
      assigns(:fr_sponsor).should eq(fr_sponsor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FrSponsor" do
        expect {
          post :create, {:fr_sponsor => valid_attributes}, valid_session
        }.to change(FrSponsor, :count).by(1)
      end

      it "assigns a newly created fr_sponsor as @fr_sponsor" do
        post :create, {:fr_sponsor => valid_attributes}, valid_session
        assigns(:fr_sponsor).should be_a(FrSponsor)
        assigns(:fr_sponsor).should be_persisted
      end

      it "redirects to the created fr_sponsor" do
        post :create, {:fr_sponsor => valid_attributes}, valid_session
        response.should redirect_to(FrSponsor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fr_sponsor as @fr_sponsor" do
        # Trigger the behavior that occurs when invalid params are submitted
        FrSponsor.any_instance.stub(:save).and_return(false)
        post :create, {:fr_sponsor => { "name" => "invalid value" }}, valid_session
        assigns(:fr_sponsor).should be_a_new(FrSponsor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FrSponsor.any_instance.stub(:save).and_return(false)
        post :create, {:fr_sponsor => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fr_sponsor" do
        fr_sponsor = FrSponsor.create! valid_attributes
        # Assuming there are no other fr_sponsors in the database, this
        # specifies that the FrSponsor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FrSponsor.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => fr_sponsor.to_param, :fr_sponsor => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested fr_sponsor as @fr_sponsor" do
        fr_sponsor = FrSponsor.create! valid_attributes
        put :update, {:id => fr_sponsor.to_param, :fr_sponsor => valid_attributes}, valid_session
        assigns(:fr_sponsor).should eq(fr_sponsor)
      end

      it "redirects to the fr_sponsor" do
        fr_sponsor = FrSponsor.create! valid_attributes
        put :update, {:id => fr_sponsor.to_param, :fr_sponsor => valid_attributes}, valid_session
        response.should redirect_to(fr_sponsor)
      end
    end

    describe "with invalid params" do
      it "assigns the fr_sponsor as @fr_sponsor" do
        fr_sponsor = FrSponsor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FrSponsor.any_instance.stub(:save).and_return(false)
        put :update, {:id => fr_sponsor.to_param, :fr_sponsor => { "name" => "invalid value" }}, valid_session
        assigns(:fr_sponsor).should eq(fr_sponsor)
      end

      it "re-renders the 'edit' template" do
        fr_sponsor = FrSponsor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FrSponsor.any_instance.stub(:save).and_return(false)
        put :update, {:id => fr_sponsor.to_param, :fr_sponsor => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fr_sponsor" do
      fr_sponsor = FrSponsor.create! valid_attributes
      expect {
        delete :destroy, {:id => fr_sponsor.to_param}, valid_session
      }.to change(FrSponsor, :count).by(-1)
    end

    it "redirects to the fr_sponsors list" do
      fr_sponsor = FrSponsor.create! valid_attributes
      delete :destroy, {:id => fr_sponsor.to_param}, valid_session
      response.should redirect_to(fr_sponsors_url)
    end
  end

end
