require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FundraiserProfilesController do

  # This should return the minimal set of attributes required to create a valid
  # FundraiserProfile. As you add validations to FundraiserProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mission" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FundraiserProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fundraiser_profiles as @fundraiser_profiles" do
      fundraiser_profile = FundraiserProfile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fundraiser_profiles).should eq([fundraiser_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested fundraiser_profile as @fundraiser_profile" do
      fundraiser_profile = FundraiserProfile.create! valid_attributes
      get :show, {:id => fundraiser_profile.to_param}, valid_session
      assigns(:fundraiser_profile).should eq(fundraiser_profile)
    end
  end

  describe "GET new" do
    it "assigns a new fundraiser_profile as @fundraiser_profile" do
      get :new, {}, valid_session
      assigns(:fundraiser_profile).should be_a_new(FundraiserProfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested fundraiser_profile as @fundraiser_profile" do
      fundraiser_profile = FundraiserProfile.create! valid_attributes
      get :edit, {:id => fundraiser_profile.to_param}, valid_session
      assigns(:fundraiser_profile).should eq(fundraiser_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FundraiserProfile" do
        expect {
          post :create, {:fundraiser_profile => valid_attributes}, valid_session
        }.to change(FundraiserProfile, :count).by(1)
      end

      it "assigns a newly created fundraiser_profile as @fundraiser_profile" do
        post :create, {:fundraiser_profile => valid_attributes}, valid_session
        assigns(:fundraiser_profile).should be_a(FundraiserProfile)
        assigns(:fundraiser_profile).should be_persisted
      end

      it "redirects to the created fundraiser_profile" do
        post :create, {:fundraiser_profile => valid_attributes}, valid_session
        response.should redirect_to(FundraiserProfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fundraiser_profile as @fundraiser_profile" do
        # Trigger the behavior that occurs when invalid params are submitted
        FundraiserProfile.any_instance.stub(:save).and_return(false)
        post :create, {:fundraiser_profile => { "mission" => "invalid value" }}, valid_session
        assigns(:fundraiser_profile).should be_a_new(FundraiserProfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FundraiserProfile.any_instance.stub(:save).and_return(false)
        post :create, {:fundraiser_profile => { "mission" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fundraiser_profile" do
        fundraiser_profile = FundraiserProfile.create! valid_attributes
        # Assuming there are no other fundraiser_profiles in the database, this
        # specifies that the FundraiserProfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FundraiserProfile.any_instance.should_receive(:update).with({ "mission" => "MyText" })
        put :update, {:id => fundraiser_profile.to_param, :fundraiser_profile => { "mission" => "MyText" }}, valid_session
      end

      it "assigns the requested fundraiser_profile as @fundraiser_profile" do
        fundraiser_profile = FundraiserProfile.create! valid_attributes
        put :update, {:id => fundraiser_profile.to_param, :fundraiser_profile => valid_attributes}, valid_session
        assigns(:fundraiser_profile).should eq(fundraiser_profile)
      end

      it "redirects to the fundraiser_profile" do
        fundraiser_profile = FundraiserProfile.create! valid_attributes
        put :update, {:id => fundraiser_profile.to_param, :fundraiser_profile => valid_attributes}, valid_session
        response.should redirect_to(fundraiser_profile)
      end
    end

    describe "with invalid params" do
      it "assigns the fundraiser_profile as @fundraiser_profile" do
        fundraiser_profile = FundraiserProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FundraiserProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => fundraiser_profile.to_param, :fundraiser_profile => { "mission" => "invalid value" }}, valid_session
        assigns(:fundraiser_profile).should eq(fundraiser_profile)
      end

      it "re-renders the 'edit' template" do
        fundraiser_profile = FundraiserProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FundraiserProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => fundraiser_profile.to_param, :fundraiser_profile => { "mission" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fundraiser_profile" do
      fundraiser_profile = FundraiserProfile.create! valid_attributes
      expect {
        delete :destroy, {:id => fundraiser_profile.to_param}, valid_session
      }.to change(FundraiserProfile, :count).by(-1)
    end

    it "redirects to the fundraiser_profiles list" do
      fundraiser_profile = FundraiserProfile.create! valid_attributes
      delete :destroy, {:id => fundraiser_profile.to_param}, valid_session
      response.should redirect_to(fundraiser_profiles_url)
    end
  end

end
