require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicProfilesController do

  # This should return the minimal set of attributes required to create a valid
  # PublicProfile. As you add validations to PublicProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "head_line" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicProfilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all public_profiles as @public_profiles" do
      public_profile = PublicProfile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:public_profiles).should eq([public_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested public_profile as @public_profile" do
      public_profile = PublicProfile.create! valid_attributes
      get :show, {:id => public_profile.to_param}, valid_session
      assigns(:public_profile).should eq(public_profile)
    end
  end

  describe "GET new" do
    it "assigns a new public_profile as @public_profile" do
      get :new, {}, valid_session
      assigns(:public_profile).should be_a_new(PublicProfile)
    end
  end

  describe "GET edit" do
    it "assigns the requested public_profile as @public_profile" do
      public_profile = PublicProfile.create! valid_attributes
      get :edit, {:id => public_profile.to_param}, valid_session
      assigns(:public_profile).should eq(public_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PublicProfile" do
        expect {
          post :create, {:public_profile => valid_attributes}, valid_session
        }.to change(PublicProfile, :count).by(1)
      end

      it "assigns a newly created public_profile as @public_profile" do
        post :create, {:public_profile => valid_attributes}, valid_session
        assigns(:public_profile).should be_a(PublicProfile)
        assigns(:public_profile).should be_persisted
      end

      it "redirects to the created public_profile" do
        post :create, {:public_profile => valid_attributes}, valid_session
        response.should redirect_to(PublicProfile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved public_profile as @public_profile" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicProfile.any_instance.stub(:save).and_return(false)
        post :create, {:public_profile => { "head_line" => "invalid value" }}, valid_session
        assigns(:public_profile).should be_a_new(PublicProfile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PublicProfile.any_instance.stub(:save).and_return(false)
        post :create, {:public_profile => { "head_line" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested public_profile" do
        public_profile = PublicProfile.create! valid_attributes
        # Assuming there are no other public_profiles in the database, this
        # specifies that the PublicProfile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PublicProfile.any_instance.should_receive(:update).with({ "head_line" => "MyText" })
        put :update, {:id => public_profile.to_param, :public_profile => { "head_line" => "MyText" }}, valid_session
      end

      it "assigns the requested public_profile as @public_profile" do
        public_profile = PublicProfile.create! valid_attributes
        put :update, {:id => public_profile.to_param, :public_profile => valid_attributes}, valid_session
        assigns(:public_profile).should eq(public_profile)
      end

      it "redirects to the public_profile" do
        public_profile = PublicProfile.create! valid_attributes
        put :update, {:id => public_profile.to_param, :public_profile => valid_attributes}, valid_session
        response.should redirect_to(public_profile)
      end
    end

    describe "with invalid params" do
      it "assigns the public_profile as @public_profile" do
        public_profile = PublicProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => public_profile.to_param, :public_profile => { "head_line" => "invalid value" }}, valid_session
        assigns(:public_profile).should eq(public_profile)
      end

      it "re-renders the 'edit' template" do
        public_profile = PublicProfile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PublicProfile.any_instance.stub(:save).and_return(false)
        put :update, {:id => public_profile.to_param, :public_profile => { "head_line" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested public_profile" do
      public_profile = PublicProfile.create! valid_attributes
      expect {
        delete :destroy, {:id => public_profile.to_param}, valid_session
      }.to change(PublicProfile, :count).by(-1)
    end

    it "redirects to the public_profiles list" do
      public_profile = PublicProfile.create! valid_attributes
      delete :destroy, {:id => public_profile.to_param}, valid_session
      response.should redirect_to(public_profiles_url)
    end
  end

end
